export const events = [
  {
    type: "Feature",
    properties: {
      mag: 4.6,
      place: "West Chile Rise",
      time: 1631474502677,
      updated: 1631996171040,
      tz: null,
      url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000fc3u",
      detail:
        "https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000fc3u&format=geojson",
      felt: null,
      cdi: null,
      mmi: null,
      alert: null,
      status: "reviewed",
      tsunami: 0,
      sig: 326,
      net: "us",
      code: "7000fc3u",
      ids: ",us7000fc3u,",
      sources: ",us,",
      types: ",origin,phase-data,",
      nst: null,
      dmin: 12.011,
      rms: 0.85,
      gap: 173,
      magType: "mb",
      type: "earthquake",
      title: "M 4.6 - West Chile Rise",
    },
    geometry: { type: "Point", coordinates: [-92.5545, -38.1792, 10] },
    id: "us7000fc3u",
  },
  {
    type: "Feature",
    properties: {
      mag: 4.2,
      place: "118 km W of San Antonio de los Cobres, Argentina",
      time: 1631454848318,
      updated: 1632150971040,
      tz: null,
      url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000fajs",
      detail:
        "https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000fajs&format=geojson",
      felt: null,
      cdi: null,
      mmi: null,
      alert: null,
      status: "reviewed",
      tsunami: 0,
      sig: 271,
      net: "us",
      code: "7000fajs",
      ids: ",us7000fajs,",
      sources: ",us,",
      types: ",origin,phase-data,",
      nst: null,
      dmin: 2.038,
      rms: 0.46,
      gap: 137,
      magType: "mb",
      type: "earthquake",
      title: "M 4.2 - 118 km W of San Antonio de los Cobres, Argentina",
    },
    geometry: { type: "Point", coordinates: [-67.4753, -24.11, 245.76] },
    id: "us7000fajs",
  },
  {
    type: "Feature",
    properties: {
      mag: 4.4,
      place: "90 km W of Illapel, Chile",
      time: 1631446353529,
      updated: 1631449783040,
      tz: null,
      url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000faim",
      detail:
        "https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000faim&format=geojson",
      felt: null,
      cdi: null,
      mmi: null,
      alert: null,
      status: "reviewed",
      tsunami: 0,
      sig: 298,
      net: "us",
      code: "7000faim",
      ids: ",us7000faim,",
      sources: ",us,",
      types: ",origin,phase-data,",
      nst: null,
      dmin: 1.026,
      rms: 0.49,
      gap: 71,
      magType: "mb",
      type: "earthquake",
      title: "M 4.4 - 90 km W of Illapel, Chile",
    },
    geometry: { type: "Point", coordinates: [-72.1176, -31.7121, 6.47] },
    id: "us7000faim",
  },
  {
    type: "Feature",
    properties: {
      mag: 4.1,
      place: "75 km W of Illapel, Chile",
      time: 1631411665345,
      updated: 1631413158040,
      tz: null,
      url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000faf0",
      detail:
        "https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000faf0&format=geojson",
      felt: null,
      cdi: null,
      mmi: null,
      alert: null,
      status: "reviewed",
      tsunami: 0,
      sig: 259,
      net: "us",
      code: "7000faf0",
      ids: ",us7000faf0,",
      sources: ",us,",
      types: ",origin,phase-data,",
      nst: null,
      dmin: 0.915,
      rms: 0.84,
      gap: 200,
      magType: "mb",
      type: "earthquake",
      title: "M 4.1 - 75 km W of Illapel, Chile",
    },
    geometry: { type: "Point", coordinates: [-71.966, -31.6868, 35] },
    id: "us7000faf0",
  },
  {
    type: "Feature",
    properties: {
      mag: 4.4,
      place: "West Chile Rise",
      time: 1631410081354,
      updated: 1631923094040,
      tz: null,
      url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000fc31",
      detail:
        "https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000fc31&format=geojson",
      felt: null,
      cdi: null,
      mmi: null,
      alert: null,
      status: "reviewed",
      tsunami: 0,
      sig: 298,
      net: "us",
      code: "7000fc31",
      ids: ",us7000fc31,",
      sources: ",us,",
      types: ",origin,phase-data,",
      nst: null,
      dmin: 18.078,
      rms: 0.75,
      gap: 102,
      magType: "mb",
      type: "earthquake",
      title: "M 4.4 - West Chile Rise",
    },
    geometry: { type: "Point", coordinates: [-93.7448, -38.2014, 10] },
    id: "us7000fc31",
  },
];
